name: tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    name: "Python ${{ matrix.python-version }} on ${{ matrix.os }}"
    runs-on: "${{ matrix.os }}"

    strategy:
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9"]
        os: [ubuntu-latest]

    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v1"
        with:
            python-version: "${{ matrix.python-version }}"
      - name: Install dependencies
        run: |
          set -xe
          pip install --upgrade pip setuptools wheel
          pip install -r requirements/requirements.txt
          pip install -r requirements/requirements-test.txt
        shell: bash
      - name: Build
        run: |
          set -xe
          python -VV
          python setup.py install
        shell: bash
      - name: Check types with pytype
        run: |
          set -xe
          pytype --version
          if [[ `python -c 'import sys; print(sys.version_info.minor)'` -le 8 ]]
          then
            pytype `find opterax/_src/ -name '*.py' | xargs` -k -d import-error
          fi
        shell: bash
      - name: Run tests
        run: |
          set -xe
          # Change directory to avoid importing the package from repo root.
          mkdir _testing && cd _testing
          python -m pytest -n "$(grep -c ^processor /proc/cpuinfo)" --pyargs opterax
          cd ..
        shell: bash
